In [1]:
import pandas as pd 
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from IPython.display import display
import os


plt.rcParams['figure.figsize'] = [40, 9]
plt.rcParams['figure.dpi']=1000

pd.options.display.max_colwidth =100
pd.set_option('display.max_rows', 1000)

<a id='the_destination'></a>

In [2]:
INITIAL_COUNT = 57
COUNTERS_DF = pd.DataFrame()
FILTERED_DF = pd.DataFrame()
FREQUENCY_ORDER_OF_NUMBERS =""
DIR_NAME = os.getcwd()

## ReadFiles

In [3]:
df2018=pd.read_csv(os.path.join(DIR_NAME, 'lottodata/2018.txt'))
df2017=pd.read_csv(os.path.join(DIR_NAME, 'lottodata/2017.txt'))
df2016=pd.read_csv(os.path.join(DIR_NAME, 'lottodata/2016.txt'))

#fromating data

dt2018 =df2018.rename(columns={'Date': 'date', 'number1' : 'n1', 'number2':'n2', 'number3':'n3', 'number4':'n4', 'number5':'n5',
       'number6':'n6', 'number7':'n7', 'jackpot clamied': 'jackpot'}, index ={})
dt2018.date= pd.to_datetime(dt2018.date)

dt2017 =df2017.rename(columns={'Date': 'date', 'number1' : 'n1', 'number2':'n2', 'number3':'n3', 'number4':'n4', 'number5':'n5',
       'number6':'n6', 'number7':'n7', 'jackpot clamied': 'jackpot'}, index ={})
dt2017.date= pd.to_datetime(dt2017.date)

dt2016 =df2016.rename(columns={'Date': 'date', 'number1' : 'n1', 'number2':'n2', 'number3':'n3', 'number4':'n4', 'number5':'n5',
       'number6':'n6', 'number7':'n7', 'jackpot clamied': 'jackpot'}, index ={})
dt2016.date= pd.to_datetime(dt2016.date)

frames = [dt2018,dt2017,dt2016]
dt = pd.concat(frames)
dt.reset_index(inplace=True, drop=True) 
print("Loaded data from :", dt.iloc[dt.date.size-1][0]," to :", dt.iloc[0][0])
dt

Loaded data from : 2016-01-02 00:00:00  to : 2018-08-01 00:00:00

          date  n1  n2  n3  n4  n5  n6  n7     jackpot
0   2018-08-01   2  22  25  32  45  46   2   5000000 R
1   2018-07-28   7  11  31  34  35  36   1   4000000 R
2   2018-07-25   8   9  39  40  41  43   9   1000000 R
3   2018-07-21   1   6   7  20  29  49   5     6931435
4   2018-07-18   5  14  19  22  33  41   1   4000000 R
5   2018-07-14  30  40  41  47  48  49   0   2000000 R
6   2018-07-11   1   3  18  28  42  44   5     5322768
7   2018-07-07   2   5  13  18  25  36   2   4000000 R
8   2018-07-04   1   5  10  25  32  37   8   1000000 R
9   2018-06-30  16  24  37  38  40  42   9    10578110
10  2018-06-27  13  17  35  37  45  46   3   5000000 R
11  2018-06-23   6  17  25  29  48  49   1   4000000 R
12  2018-06-20   6  22  31  33  36  43   5   1000000 R
13  2018-06-16   4  19  31  33  40  46   2     8098317
14  2018-06-13   3   4   6  10  46  48   3   5000000 R
15  2018-06-09  13  16  34  35  39  42   9   4000000 R
16  2018-06-06   3   8  13  15  18  42   6   1000000 R
17  2018-06-02   1  10  19  24  30  31   7     3433497
18  2018-05-30  15  23  29  35  38  48   2   4000000 R
19  2018-05-26  10  16  24  27  47  48   6   3000000 R
20  2018-05-23   7  16  29  36  45  47   6    11352208
21  2018-05-19   3   4  27  41  44  49   2   6000000 R
22  2018-05-16   2  12  13  19  34  46   9   4000000 R
23  2018-05-12  23  27  29  36  38  42   0   3000000 R
24  2018-05-09   3   9  25  31  37  43   5     8299495
25  2018-05-05   1   5  17  31  34  49   7   7000000 R
26  2018-05-02   3   5  12  19  42  44   7   4000000 R
27  2018-04-28   2   9  11  33  47  48   4   2000000 R
28  2018-04-25   4   6  10  11  17  25   6     8298865
29  2018-04-21  12  15  19  23  29  38   5   7000000 R
30  2018-04-18   2   4   7  10  35  37   8   4000000 R
31  2018-04-14   4   9  33  34  42  47   6   3000000 R
32  2018-04-11   9  20  25  27  44  48   5     2047240
33  2018-04-07  12  15  19  27  34  47   8     7135159
34  2018-04-04  13  23  28  30  33  46   7   4000000 R
35  2018-03-31   1   8  12  15  46  48   5   3000000 R
36  2018-03-28   1  23  25  31  38  47   7     2490206
37  2018-03-24   3  16  27  34  42  45   1   3000000 R
38  2018-03-21  20  26  29  38  43  48   0    14033932
39  2018-03-17   1   7  17  22  29  46   7  11000000 R
40  2018-03-14  13  18  30  38  45  48   7   8000000 R
41  2018-03-10   8  19  34  35  40  49   8   7000000 R
42  2018-03-07   5  24  28  30  35  42   1   4000000 R
43  2018-03-03   5  24  28  37  40  44   8   3000000 R
44  2018-02-28   6  15  32  36  43  47   6     1337526
45  2018-02-24  18  27  33  41  44  47   6     8544076
46  2018-02-17  15  18  26  27  37  42   2   1000000 R
47  2018-02-10  17  20  27  35  41  45   8     7366168
48  2018-02-07  15  20  25  28  33  41   5   4000000 R
49  2018-02-03   5   9  13  20  39  48   5   3000000 R
50  2018-01-31   3   6   8  26  29  38   8     8813840
51  2018-01-27   4  22  24  34  36  43   6   7000000 R
52  2018-01-24   3   5  18  31  37  45   7   4000000 R
53  2018-01-20   3  11  15  18  33  45   4   3000000 R
54  2018-01-17   3  13  25  27  32  48   2    16244272
55  2018-01-13   5   6  14  16  31  48   0  14000000 R
56  2018-01-10   3  22  24  25  43  45   6  11000000 R
57  2018-01-06   5  14  32  37  46  47   0  10000000 R
58  2018-01-03  10  15  31  34  35  45   8   6000000 R
59  2017-12-30  11  12  14  27  37  48   0   5000000 R
60  2017-12-27  17  19  31  37  45  46   0   1000000 R
61  2017-12-23   4  11  31  32  38  39   6    18961293
62  2017-12-20   8  13  35  38  39  44   4  15000000 R
63  2017-12-16   5   6  18  23  30  40   9  13000000 R
64  2017-12-13   2   3   9  14  17  27   0  10000000 R
65  2017-12-09   7  12  16  20  25  46   7   8000000 R
66  2017-12-06  11  18  19  29  35  43   9   5000000 R
67  2017-12-02   3  12  13  17  18  33   2   4000000 R
68  2017-11-29   9  16  25  28  30  32   8   1000000 R
69  2017-11-25  11  17  20  26  37  43   9     8574680
70  2017-11-22  24  28  29  32  34  48   9   5000000 R
71  2017-11-18   2   5   9  12  20  35   7   4000000 R
72  2017-11-15   6  23  35  40  45  46   5   1000000 R
73  2017-11-11   1   7  11  16  19  37   7    17830561
74  2017-11-08   7  14  24  37  38  43   7  14000000 R
75  2017-11-04   3   7  14  21  46  47   6  13000000 R
76  2017-11-01   3   8  15  18  21  31   9  10000000 R
77  2017-10-28   1  20  22  24  33  36   1   8000000 R
78  2017-10-25   1  18  29  32  36  42   8   5000000 R
79  2017-10-21   4  10  15  25  34  46   1   4000000 R
80  2017-10-18   4   7  10  11  13  38   4   1000000 R
81  2017-10-14   7   9  10  13  35  40   7    13121323
82  2017-10-11   3   6  17  20  21  42   7  10000000 R
83  2017-10-07  11  20  21  24  30  49   6   8000000 R
84  2017-10-04  11  15  16  17  19  45   4   5000000 R
85  2017-09-30   4  18  19  23  33  46   1   4000000 R
86  2017-09-27  17  20  25  31  33  37   6   1000000 R
87  2017-09-23  10  15  19  23  38  44   6     8537139
88  2017-09-20   3   9  28  30  36  46   3   5000000 R
89  2017-09-16  21  26  27  31  35  47   9   4000000 R
90  2017-09-13  11  16  17  18  30  40   6   1000000 R
91  2017-09-09   8  14  18  27  40  49   3    17629073
92  2017-09-06  12  16  19  28  33  48   3  14000000 R
93  2017-09-02   3   5   8  14  33  34   6  12000000 R
94  2017-08-30   5   7   9  21  29  34   3   9000000 R
95  2017-08-26   2  11  19  24  28  49   9   8000000 R
96  2017-08-23  16  23  25  28  32  49   6   5000000 R
97  2017-08-19   2  10  29  35  45  48   2   4000000 R
98  2017-08-16   6   9  29  36  38  49   3   1000000 R
99  2017-08-12   5  15  25  27  47  49   6     3594929
100 2017-08-09   1  10  18  39  41  49   7   4000000 R
101 2017-08-05  14  18  19  23  37  49   5   3000000 R
102 2017-08-02  21  22  23  34  36  49   5    14789463
103 2017-07-29  14  20  29  30  35  37   3  13000000 R
104 2017-07-26  12  15  18  26  27  33   0  10000000 R
105 2017-07-22   5  27  37  41  45  47   7   8000000 R
106 2017-07-19  17  19  21  27  36  41   1   5000000 R
107 2017-07-15   8  25  31  32  33  38   1   4000000 R
108 2017-07-12  18  22  30  36  44  49   7   1000000 R
109 2017-07-08   2   3  17  23  27  40   2    13173447
110 2017-07-05   7  33  34  39  40  47   0  10000000 R
111 2017-07-01   2   3  15  22  35  47   8   8000000 R
112 2017-06-28  13  17  29  38  41  42   4   5000000 R
113 2017-06-24  13  23  27  38  43  46   6   4000000 R
114 2017-06-21   4   6   7  39  41  44   4   1000000 R
115 2017-06-17   2   6  16  22  44  49   1     7287855
116 2017-06-14  29  30  32  33  36  44   1   4000000 R
117 2017-06-10   4   6  16  26  29  42   7   3000000 R
118 2017-06-07   6  17  18  28  33  37   4    29696697
119 2017-06-03  24  31  32  35  37  46   3  27000000 R
120 2017-05-31   9  17  24  27  36  48   7  24000000 R
121 2017-05-27  23  24  25  27  29  49   1  22000000 R
122 2017-05-24   6  13  19  25  26  44   3  19000000 R
123 2017-05-20   1  15  29  34  37  44   7  17000000 R
124 2017-05-17   1   2  23  26  36  43   3  14000000 R
125 2017-05-13   7  19  32  45  47  48   1  13000000 R
126 2017-05-10   9  18  26  38  39  42   8  10000000 R
127 2017-05-06  16  26  30  31  32  47   4   8000000 R
128 2017-05-03   4   5  12  18  20  33   8   5000000 R
129 2017-04-29   3   4  18  36  37  49   5   4000000 R
130 2017-04-26  25  31  34  37  39  42   3   1000000 R
131 2017-04-22   1  11  12  19  25  32   7    13245614
132 2017-04-19  19  23  27  30  41  48   0  10000000 R
133 2017-04-15  12  18  21  27  30  36   7   8000000 R
134 2017-04-12  10  11  14  24  26  48   5   5000000 R
135 2017-04-08   2   7  28  39  40  47   1   4000000 R
136 2017-04-05   1   6   7  22  41  49   2   1000000 R
137 2017-04-01   5   8   9  18  22  36   8  11300368 R
138 2017-03-29   9  21  24  25  28  47   2   5000000 R
139 2017-03-25   1   9  11  25  26  49   6   4000000 R
140 2017-03-22   4  15  18  21  22  38   6   1000000 R
141 2017-03-18   4  12  23  27  31  40   0     5896029
142 2017-03-15   7  15  16  25  26  40   1  20000000 R
143 2017-03-11   4  12  17  26  46  49   8  18000000 R
144 2017-03-08   3   7  16  26  28  35   6  15000000 R
145 2017-03-04   1  19  22  23  41  45   2  13000000 R
146 2017-03-01  12  22  29  30  31  38   4  10000000 R
147 2017-02-25   1   3   4   9  28  32   4   8000000 R
148 2017-02-22   1   5   7  25  42  46   3   5000000 R
149 2017-02-18  17  20  24  25  27  41   9   4000000 R
150 2017-02-15   7  13  18  33  36  39   4   1000000 R
151 2017-02-11   3  12  22  32  45  46   6     4495389
152 2017-02-08  14  22  28  30  41  46   6   6000000 R
153 2017-02-04   2  16  28  37  39  49   8   4000000 R
154 2017-02-01   3  13  19  21  25  42   9   1000000 R
155 2017-01-28   6   9  15  38  41  42   7     3057019
156 2017-01-25   1   2  14  17  25  49   5    31058057
157 2017-01-21   5   9  11  14  26  39   9  29000000 R
158 2017-01-18  10  11  13  28  39  40   1  25000000 R
159 2017-01-14   3   4  23  27  28  37   3  23000000 R
160 2017-01-11  20  27  29  32  34  38   1  20000000 R
161 2017-01-07  12  14  17  22  45  46   7  18000000 R
162 2017-01-04   5  13  21  37  39  48   2  15000000 R
163 2016-12-31  27  29  37  42  45  47   3  13000000 R
164 2016-12-28   1   3   4  22  29  30   3   9000000 R
165 2016-12-24   4  11  18  22  30  45   1   7000000 R
166 2016-12-21   3  21  23  38  39  42   7   4000000 R
167 2016-12-17   6  24  28  29  34  35   2   3000000 R
168 2016-12-14  33  34  38  42  43  44   4      691276
169 2016-12-10  11  17  32  34  37  49   3     7578027
170 2016-12-07  13  18  36  40  42  48   8   4000000 R
171 2016-12-03   5  16  39  43  47  48   9   3000000 R
172 2016-11-30   1  10  12  19  21  47   6     1415102
173 2016-11-26  26  32  41  42  45  47   9     2904766
174 2016-11-23   4  27  28  31  38  44   7     6533986
175 2016-11-19   1   2   6  15  38  39   3   4000000 R
176 2016-11-16  13  19  20  38  39  44   8   1000000 R
177 2016-11-12   2   6   9  19  20  47   1   4379578 R
178 2016-11-09   6  13  20  33  39  41   5   5000000 R
179 2016-11-05   9  32  35  38  42  43   8   4000000 R
180 2016-11-02   1  12  19  26  30  48   6   1000000 R
181 2016-10-29   5   7   8  26  28  36   8     8760598
182 2016-10-26  11  15  18  43  44  45   6   5000000 R
183 2016-10-22   2  21  26  32  36  48   7   4000000 R
184 2016-10-19  16  32  33  40  42  43   5   1000000 R
185 2016-10-15   7  13  19  29  38  41   9    13568089
186 2016-10-12  22  29  35  37  39  47   2  10000000 R
187 2016-10-08  14  21  32  33  35  48   5   8000000 R
188 2016-10-05   1   5   6  17  28  41   1   5000000 R
189 2016-10-01   7  20  25  26  34  37   1   4000000 R
190 2016-09-28  11  15  38  41  44  46   2   1000000 R
191 2016-09-24   4  15  18  21  32  45   4     4344796
192 2016-09-21   1   8  11  18  24  29   5   1000000 R
193 2016-09-17   3  34  35  37  46  47   2     3083198
194 2016-09-14   2   3  15  20  31  35   8         NaN
195 2016-09-10   1   3   6  11  24  43   0  29000000 R
196 2016-09-07   7  11  18  19  21  27   0  25000000 R
197 2016-09-03   8  14  18  25  30  36   1  23000000 R
198 2016-08-31   3   7  31  37  40  41   3  20000000 R
199 2016-08-27   1   8  22  32  33  43   9  18000000 R
200 2016-08-24   6  14  16  35  42  48   2  15000000 R
201 2016-08-20  23  28  30  31  37  45   5  13000000 R
202 2016-08-17   2  10  30  34  41  49   1  10000000 R
203 2016-08-13   6  14  28  30  37  39   2   9000000 R
204 2016-08-10  11  12  17  23  43  49   9   6000000 R
205 2016-08-06   6  25  26  33  45  47   0   4000000 R
206 2016-08-03  15  21  26  34  42  43   6   1000000 R
207 2016-07-30   6  13  23  26  30  33   2    28932056
208 2016-07-27   5   6   7  17  18  39   1  25000000 R
209 2016-07-23   5  25  29  43  47  48   5  23000000 R
210 2016-07-20   1  18  20  28  40  49   5  20000000 R
211 2016-07-16   1  18  22  30  34  44   5  18000000 R
212 2016-07-13  10  14  20  27  33  41   7  15000000 R
213 2016-07-09   1  34  37  40  44  49   7  13000000 R
214 2016-07-06   4  16  18  37  38  42   0  10000000 R
215 2016-07-02   4   6   8  15  26  30   9   8000000 R
216 2016-06-29   4   5  28  32  44  49   4   5000000 R
217 2016-06-25   2   6  10  11  34  44   3   4000000 R
218 2016-06-22   8  19  35  40  41  43   8   1000000 R
219 2016-06-18   2   8  12  17  19  27   1     2996813
220 2016-06-15   7  12  13  33  48  49   7     8994882
221 2016-06-11   6  13  21  27  38  45   5   7000000 R
222 2016-06-08   2   5  30  33  44  48   6   4000000 R
223 2016-06-04   5   6  22  31  35  42   3   3000000 R
224 2016-06-01  19  25  30  35  40  46   2     4535875
225 2016-05-28   5   9  17  24  39  45   3   7000000 R
226 2016-05-25   6   9  10  21  30  36   6   4000000 R
227 2016-05-21   2   5  29  46  47  48   4   3000000 R
228 2016-05-18  10  13  19  26  31  41   4     1455100
229 2016-05-14   5  13  15  26  30  44   9         NaN
230 2016-05-11  10  19  20  31  39  41   5  30000000 R
231 2016-05-07  16  32  34  37  42  44   9  28000000 R
232 2016-05-04   2  11  14  35  39  49   5  24000000 R
233 2016-04-30  14  26  28  30  36  43   6  22000000 R
234 2016-04-27   1   6   9  21  26  37   6  18000000 R
235 2016-04-23   8  15  16  17  27  35   4  17000000 R
236 2016-04-20   1   5  11  13  20  49   8  13000000 R
237 2016-04-16   5  14  15  20  22  38   9  12000000 R
238 2016-04-13   2  13  17  35  36  49   7   9000000 R
239 2016-04-09   1   4  38  39  46  47   2   7000000 R
240 2016-04-06   6  19  25  30  33  42   4   4000000 R
241 2016-04-02   1  10  17  23  28  38   6   3000000 R
242 2016-03-30   1   5   9  13  26  41   1     5319644
243 2016-03-26   1   3  31  33  40  41   5   3000000 R
244 2016-03-23   9  10  16  22  31  44   0     9106378
245 2016-03-19   4  10  15  37  44  49   5   7000000 R
246 2016-03-16   9  11  26  29  35  46   6   4000000 R
247 2016-03-12  20  26  30  39  47  49   4   3000000 R
248 2016-03-09  10  13  32  37  46  48   7     6019797
249 2016-03-05   7  10  33  37  43  46   3   4000000 R
250 2016-03-02   1   8  10  16  17  40   9   1000000 R
251 2016-02-27   7  10  15  25  37  49   7     4466455
252 2016-02-24   5  13  23  31  47  48   5   1000000 R
253 2016-02-20   1  13  16  29  30  31   6     4529955
254 2016-02-17  24  26  32  35  38  39   3   1000000 R
255 2016-02-13  18  20  30  32  43  45   8     9649160
256 2016-02-10   2  17  19  32  34  38   4  15000000 R
257 2016-02-06  10  16  25  28  34  49   5  14000000 R
258 2016-02-03  10  18  19  31  33  47   8  10000000 R
259 2016-01-30  18  23  33  34  40  48   9   9000000 R
260 2016-01-27  12  14  16  19  29  47   3   5000000 R
261 2016-01-23   2  16  25  26  27  40   0   4000000 R
262 2016-01-20   7  12  14  15  19  46   3   1000000 R
263 2016-01-16   9  21  23  31  34  39   8     4502793
264 2016-01-13  14  18  19  25  35  46   0   1000000 R
265 2016-01-09  10  13  31  34  46  48   6     6850686
266 2016-01-06   3  12  27  36  42  45   0  10000000 R
267 2016-01-02   1  23  30  35  43  47   8   9000000 R

## Define Functions

In [4]:

def do_calculate_frequency(filter_df):
    n1c=Counter(filter_df.n1)
    n2c=Counter(filter_df.n2)
    n3c=Counter(filter_df.n3)
    n4c=Counter(filter_df.n4)
    n5c=Counter(filter_df.n5)
    n6c=Counter(filter_df.n6)
    sum1 = n1c+n2c+n3c+n4c+n5c+n6c
    data = [sum1,n1c,n2c,n3c,n4c,n5c,n6c]
    index = ["sum","first", "second", "third", "forth", "fifth", "six"]
    temp =pd.DataFrame(data, index=index)
    temp=temp.replace(np.nan,0)
    temp=temp.astype('int')
    datacounter=temp.transpose()
    datacounter=datacounter.sort_values(by='sum', ascending=False)    
    return datacounter

def do_counter_barplot(datacounter):  
    
    #plt.figure(figsize=(40, 9), dpi= 1000, facecolor='w', edgecolor='k')
    #datacounter.plot.hist(alpha=1)
    plt.rcParams['figure.figsize'] = [9, 2.5]
    plt.rcParams['figure.dpi']=200
    plt.figure()
    datacounter.plot.bar()

def do_print_counter(datacounter):
    t = datacounter
    t['position'] = pd.Series(np.array(range(1,datacounter.index.size+1,1)), index=datacounter.index)
    global COUNTERS_DF 
    COUNTERS_DF = t
    #t = datacounter.transpose()    
    #t['index'] = pd.series(range(1,49,1))
    #t.style.set_include_index(True) 
    #display(t.style)    
    display(t.transpose().style)

## Frequency of numbers

In [5]:
import ipywidgets as widgets
from ipywidgets import interact, HBox, Label

def view(y=INITIAL_COUNT):
    filter_df = dt.head(y)
    print("starting from date :", filter_df.iloc[filter_df.date.size-1][0] )
    print("number of draws :", y ,"from " , filter_df.iloc[0][0] )
    counters = do_calculate_frequency(filter_df=filter_df)
    do_counter_barplot(datacounter = counters)
    do_print_counter(datacounter = counters)
    
    global FILTERED_DF 
    FILTERED_DF = filter_df
    
    global COUNTERS_DF 
    COUNTERS_DF = counters
    
    #do_order_of_frequency(a)
    #print(counters.transpose())
    #return

style = {'description_width': 'initial'}
a_slider = widgets.BoundedIntText(min=0, max=dt.date.size, step=1, value=INITIAL_COUNT, description='number of entries: ', sytle=style)
widgets.interact(view,y=a_slider)

interactive(children=(BoundedIntText(value=57, description='number of entries: ', max=268), Output()), _dom_cl…

## Find the Position of the draw from  the counts

In [6]:
def do_order_of_frequency(a =[1,1,1,1,1,11]):
    i=0
    order = []
    return_string = "order of " + str(a) +": "
    
    while i < len(a) : 
        #return_string += str(a[i]) + " : " + str(COUNTERS_DF.iloc[COUNTERS_DF.index.get_loc(a[i])][7])+ " , " 
        #order[i] = COUNTERS_DF.iloc[COUNTERS_DF.index.get_loc(a[i])][7]
        try:
            order.append(COUNTERS_DF.iloc[COUNTERS_DF.index.get_loc(a[i])][7])
        except KeyError:
            order.append(-1)
        #return_string += str(COUNTERS_DF.iloc[COUNTERS_DF.index.get_loc(a[i])][7])+ " , " 
        i += 1
    #print(order)
    global FREQUENCY_ORDER_OF_NUMBERS
    FREQUENCY_ORDER_OF_NUMBERS = return_string + str(order) + " , [Max, Min]: [" + str(max(order)) + " , " +str(min(order)) +" , " + str(np.mean(order))+ "]"
    return FREQUENCY_ORDER_OF_NUMBERS        
a = [7,11,31,34,35,36]
do_order_of_frequency(a)    
print(do_order_of_frequency(a))
a = [8,9,39,40,41,43]    
print(do_order_of_frequency(a))
a = [1,6,7,20,29,49]    
print(do_order_of_frequency(a))
a = [5,14,19,22,33,41]    
print(do_order_of_frequency(a))
a = [30,40,41,47,48,49]    
print(do_order_of_frequency(a))
a = [1,3,18,28,42,44]    
print(do_order_of_frequency(a))
a = [2,5,13,18,25,36]    
print(do_order_of_frequency(a))
a = [1,5,10,25,32,37]    
print(do_order_of_frequency(a))

a_slider
#FREQUENCY_ORDER_OF_NUMBERS

order of [7, 11, 31, 34, 35, 36]: [40, 45, 11, 10, 18, 23] , [Max, Min]: [45 , 10 , 24.5]
order of [8, 9, 39, 40, 41, 43]: [42, 36, 46, 29, 25, 27] , [Max, Min]: [46 , 25 , 34.166666666666664]
order of [1, 6, 7, 20, 29, 49]: [20, 17, 40, 34, 9, 30] , [Max, Min]: [40 , 9 , 25.0]
order of [5, 14, 19, 22, 33, 41]: [4, 48, 21, 33, 12, 25] , [Max, Min]: [48 , 4 , 23.833333333333332]
order of [30, 40, 41, 47, 48, 49]: [41, 29, 25, 14, 1, 30] , [Max, Min]: [41 , 1 , 23.333333333333332]
order of [1, 3, 18, 28, 42, 44]: [20, 2, 22, 37, 6, 28] , [Max, Min]: [37 , 2 , 19.166666666666668]
order of [2, 5, 13, 18, 25, 36]: [38, 4, 8, 22, 3, 23] , [Max, Min]: [38 , 3 , 16.333333333333332]
order of [1, 5, 10, 25, 32, 37]: [20, 4, 32, 3, 44, 15] , [Max, Min]: [44 , 3 , 19.666666666666668]

BoundedIntText(value=57, description='number of entries: ', max=268)

## Most common pairs

In [7]:
#print(COUNTERS_DF.index.get_loc(7))
COUNTERS_DF.iloc[COUNTERS_DF.index.get_loc(7)][7]

40

In [8]:
#FILTERED_DF
FILTERED_DF.shape[1]
#for i in range(FILTERED_DF.shape[1])

9

In [13]:
items_to_take=20
def do_filter_dt(start_from,number_of_items):
    filter_df = dt.iloc[start_from:start_from+number_of_items,:]
    #print("starting from date :", filter_df.iloc[filter_df.date.size-1][0] )
    #print("number of draws :", y ,"from " , filter_df.iloc[0][0] )
    counters = do_calculate_frequency(filter_df=filter_df)
    #t = counters
    counters['position'] = pd.Series(np.array(range(1,counters.index.size+1,1)), index=counters.index)
    
    #display(filter_df.transpose().style)
    #display(counters.transpose().style)
    global FILTERED_DF 
    FILTERED_DF = filter_df
    
    global COUNTERS_DF 
    COUNTERS_DF = counters
    
def do_order_of_frequency(a , counters_df):
    i=0
    order = []
    return_string = "order of " + str(a) +": "
    
    while i < len(a) : 
        try:
            order.append(counters_df.iloc[counters_df.index.get_loc(a[i])][7])
        except KeyError:
            order.append(-1)
        #return_string += str(COUNTERS_DF.iloc[COUNTERS_DF.index.get_loc(a[i])][7])+ " , " 
        i += 1
    #print(order)
    order_only_number = [x for x in order if x != -1]
    print(order_only_number)
    global FREQUENCY_ORDER_OF_NUMBERS
    
    try:
        if len(order_only_number) > 5:
            FREQUENCY_ORDER_OF_NUMBERS = return_string + str(order) + " , [Max, Min]: [" + str(max(order_only_number)) + " , " +str(min(order_only_number)) +" , " + str(np.mean(order_only_number))+ "] \nordered: " + str(np.sort(order_only_number)) + " count :" + str(len(order_only_number) ) 
        else :
            FREQUENCY_ORDER_OF_NUMBERS= "0"
        #FREQUENCY_ORDER_OF_NUMBERS =  "\nordered: " + str(np.sort(order_only_number)) + " count :" + str(len(order_only_number)) 
    except:
        print("error")
    #FREQUENCY_ORDER_OF_NUMBERS = return_string + str(order) + " , [Max, Min]: [" + str(max(order_only_number)) + " , " +str(min(order_only_number)) +" , " + str(np.mean(order_only_number))+ "] "

    return FREQUENCY_ORDER_OF_NUMBERS

i=1 
number_of_items = 6
while i < 200 :
    do_filter_dt(i,number_of_items)
    #list(dt.iloc[0,1:6])
    print("index: " + str(i-1) +" " + do_order_of_frequency(a=list(dt.iloc[i-1,1:7]), counters_df=COUNTERS_DF) +  " counters size: " +str(COUNTERS_DF.shape) )
    i +=1

[24]
index: 0 0 counters size: (30, 8)
[7, 16]
index: 1 0 counters size: (29, 8)
[14, 4]
index: 2 0 counters size: (28, 8)
[2, 27]
index: 3 0 counters size: (27, 8)
[3, 14]
index: 4 0 counters size: (27, 8)
[14, 10, 26]
index: 5 0 counters size: (26, 8)
[8, 24, 14]
index: 6 0 counters size: (27, 8)
[26, 24, 8, 14]
index: 7 0 counters size: (27, 8)
[24, 18, 7]
index: 8 0 counters size: (25, 8)
[23, 10, 14, 13]
index: 9 0 counters size: (25, 8)
[6, 21, 14, 5]
index: 10 0 counters size: (26, 8)
[3, 25]
index: 11 0 counters size: (25, 8)
[24, 11, 12]
index: 12 0 counters size: (25, 8)
[13, 24, 17, 12]
index: 13 0 counters size: (25, 8)
[19, 4, 2]
index: 14 0 counters size: (25, 8)
[23, 6, 10, 13]
index: 15 0 counters size: (27, 8)
[27, 23, 22]
index: 16 0 counters size: (28, 8)
[23, 19, 18]
index: 17 0 counters size: (26, 8)
[21, 2, 15, 8]
index: 18 0 counters size: (29, 8)
[27, 1, 9]
index: 19 0 counters size: (29, 8)
[21, 18]
index: 20 0 counters size: (25, 8)
[2, 21, 13, 27]
index: 21 0 counters size: (27, 8)
[21, 24, 23, 11]
index: 22 0 counters size: (28, 8)
[19, 21, 10, 11]
index: 23 0 counters size: (27, 8)
[27, 24, 22, 20, 11]
index: 24 0 counters size: (28, 8)
[12, 23, 11]
index: 25 0 counters size: (25, 8)
[10, 23, 14, 13]
index: 26 0 counters size: (25, 8)
[11, 4, 22, 18, 3, 25]
index: 27 order of [2, 9, 11, 33, 47, 48]: [11, 4, 22, 18, 3, 25] , [Max, Min]: [25 , 3 , 13.833333333333334]
ordered: [ 3  4 11 18 22 25] count :6 counters size: (25, 8)
[3, 24, 21]
index: 28 0 counters size: (26, 8)
[6, 7, 21, 19]
index: 29 0 counters size: (26, 8)
[15]
index: 30 0 counters size: (23, 8)
[12, 25, 5, 15, 3]
index: 31 0 counters size: (25, 8)
[11, 25, 7, 8]
index: 32 0 counters size: (26, 8)
[19, 7, 28, 15, 9]
index: 33 0 counters size: (28, 8)
[26, 19, 15, 4]
index: 34 0 counters size: (27, 8)
[2, 27, 8, 4]
index: 35 0 counters size: (29, 8)
[9, 4]
index: 36 0 counters size: (28, 8)
[17, 14, 11]
index: 37 0 counters size: (27, 8)
[20, 9, 11, 16]
index: 38 0 counters size: (30, 8)
[]
index: 39 0 counters size: (27, 8)
[4, 20]
index: 40 0 counters size: (24, 8)
[7, 19]
index: 41 0 counters size: (23, 8)
[15, 21, 9, 17, 13]
index: 42 0 counters size: (23, 8)
[8, 19, 15, 11]
index: 43 0 counters size: (25, 8)
[25, 4, 10]
index: 44 0 counters size: (26, 8)
[23, 2, 16, 3]
index: 45 0 counters size: (30, 8)
[25, 23, 19, 17, 10]
index: 46 0 counters size: (30, 8)
[6, 10, 3]
index: 47 0 counters size: (28, 8)
[26, 24, 21, 15]
index: 48 0 counters size: (28, 8)
[6, 9, 5]
index: 49 0 counters size: (27, 8)
[1, 23]
index: 50 0 counters size: (23, 8)
[12, 13, 19]
index: 51 0 counters size: (22, 8)
[1, 6, 10, 5, 20, 2]
index: 52 order of [3, 5, 18, 31, 37, 45]: [1, 6, 10, 5, 20, 2] , [Max, Min]: [20 , 1 , 7.333333333333333]
ordered: [ 1  2  5  6 10 20] count :6 counters size: (25, 8)
[9, 17, 14, 4]
index: 53 0 counters size: (24, 8)
[14, 15, 8, 13, 5]
index: 54 0 counters size: (25, 8)
[25, 6, 1, 26]
index: 55 0 counters size: (26, 8)
[6]
index: 56 0 counters size: (24, 8)
[16, 22, 14, 6, 10]
index: 57 0 counters size: (28, 8)
[7, 15, 12]
index: 58 0 counters size: (28, 8)
[24, 23, 21, 14, 10]
index: 59 0 counters size: (31, 8)
[20, 17, 12, 31]
index: 60 0 counters size: (31, 8)
[23, 12, 13]
index: 61 0 counters size: (29, 8)
[22, 14]
index: 62 0 counters size: (27, 8)
[8, 16]
index: 63 0 counters size: (25, 8)
[17, 24, 7]
index: 64 0 counters size: (25, 8)
[5, 22, 9, 19]
index: 65 0 counters size: (25, 8)
[26, 23, 12, 2, 14]
index: 66 0 counters size: (29, 8)
[24, 23]
index: 67 0 counters size: (28, 8)
[25, 22, 8, 14]
index: 68 0 counters size: (28, 8)
[24, 20, 4, 11]
index: 69 0 counters size: (29, 8)
[14]
index: 70 0 counters size: (28, 8)
[19, 15]
index: 71 0 counters size: (27, 8)
[11]
index: 72 0 counters size: (25, 8)
[1, 3, 15]
index: 73 0 counters size: (26, 8)
[3, 22, 20, 13]
index: 74 0 counters size: (26, 8)
[21, 4, 22, 27]
index: 75 0 counters size: (27, 8)
[20, 23, 21, 17]
index: 76 0 counters size: (27, 8)
[17, 8, 20, 13]
index: 77 0 counters size: (27, 8)
[13]
index: 78 0 counters size: (25, 8)
[7, 5, 23, 16]
index: 79 0 counters size: (26, 8)
[19, 26, 24, 4, 23]
index: 80 0 counters size: (28, 8)
[23]
index: 81 0 counters size: (25, 8)
[10, 6, 7, 21]
index: 82 0 counters size: (26, 8)
[25, 22, 21, 16]
index: 83 0 counters size: (28, 8)
[25, 24, 23, 2, 4]
index: 84 0 counters size: (28, 8)
[4, 23, 20, 15, 9]
index: 85 0 counters size: (30, 8)
[22, 15, 14]
index: 86 0 counters size: (29, 8)
[25]
index: 87 0 counters size: (26, 8)
[11, 24, 19, 12]
index: 88 0 counters size: (26, 8)
[16, 18]
index: 89 0 counters size: (24, 8)
[22, 8, 20, 12]
index: 90 0 counters size: (25, 8)
[21, 11, 9]
index: 91 0 counters size: (25, 8)
[24, 23, 5, 15, 10]
index: 92 0 counters size: (27, 8)
[3, 15]
index: 93 0 counters size: (26, 8)
[17, 21, 3]
index: 94 0 counters size: (27, 8)
[19, 20, 18, 1]
index: 95 0 counters size: (27, 8)
[6, 27, 1]
index: 96 0 counters size: (27, 8)
[23, 2, 12]
index: 97 0 counters size: (26, 8)
[17, 12, 1]
index: 98 0 counters size: (26, 8)
[21, 8, 6, 10, 1]
index: 99 0 counters size: (26, 8)
[8, 4, 7]
index: 100 0 counters size: (24, 8)
[27, 24, 23, 20, 3, 29]
index: 101 order of [14, 18, 19, 23, 37, 49]: [27, 24, 23, 20, 3, 29] , [Max, Min]: [29 , 3 , 21.0]
ordered: [ 3 20 23 24 27 29] count :6 counters size: (29, 8)
[21, 20, 6, 28]
index: 102 0 counters size: (28, 8)
[7, 13]
index: 103 0 counters size: (28, 8)
[24, 1, 7]
index: 104 0 counters size: (28, 8)
[8, 11, 3]
index: 105 0 counters size: (27, 8)
[4, 20, 13, 11]
index: 106 0 counters size: (28, 8)
[20, 2]
index: 107 0 counters size: (26, 8)
[13, 22]
index: 108 0 counters size: (24, 8)
[1, 18, 22, 21, 20, 15]
index: 109 order of [2, 3, 17, 23, 27, 40]: [1, 18, 22, 21, 20, 15] , [Max, Min]: [22 , 1 , 16.166666666666668]
ordered: [ 1 15 18 20 21 22] count :6 counters size: (26, 8)
[25, 17, 14, 10]
index: 110 0 counters size: (27, 8)
[10, 21]
index: 111 0 counters size: (24, 8)
[25, 24, 3, 13, 11, 10]
index: 112 order of [13, 17, 29, 38, 41, 42]: [25, 24, 3, 13, 11, 10] , [Max, Min]: [25 , 3 , 14.333333333333334]
ordered: [ 3 10 11 13 24 25] count :6 counters size: (27, 8)
[10]
index: 113 0 counters size: (25, 8)
[18, 1, 6]
index: 114 0 counters size: (25, 8)
[8, 23, 12, 25]
index: 115 0 counters size: (25, 8)
[8, 18, 10, 15, 13]
index: 116 0 counters size: (26, 8)
[7, 19, 8]
index: 117 0 counters size: (26, 8)
[22, 12, 4]
index: 118 0 counters size: (25, 8)
[9, 16, 19]
index: 119 0 counters size: (25, 8)
[25, 26, 23, 18, 10]
index: 120 0 counters size: (28, 8)
[20, 19, 18]
index: 121 0 counters size: (28, 8)
[22, 1, 8]
index: 122 0 counters size: (30, 8)
[7, 14]
index: 123 0 counters size: (28, 8)
[7, 14]
index: 124 0 counters size: (26, 8)
[20, 3, 11]
index: 125 0 counters size: (25, 8)
[2, 21, 13, 10]
index: 126 0 counters size: (27, 8)
[9, 18, 17]
index: 127 0 counters size: (25, 8)
[25, 3, 4]
index: 128 0 counters size: (26, 8)
[20, 17, 16]
index: 129 0 counters size: (28, 8)
[18, 12]
index: 130 0 counters size: (27, 8)
[16, 22, 21, 19]
index: 131 0 counters size: (28, 8)
[16, 15, 12, 11]
index: 132 0 counters size: (27, 8)
[13, 14, 19]
index: 133 0 counters size: (24, 8)
[11, 15, 17]
index: 134 0 counters size: (24, 8)
[23, 17, 13, 11]
index: 135 0 counters size: (26, 8)
[16, 23, 3, 25]
index: 136 0 counters size: (25, 8)
[5, 19, 18]
index: 137 0 counters size: (24, 8)
[23, 19, 9, 14]
index: 138 0 counters size: (24, 8)
[17, 19, 2, 25]
index: 139 0 counters size: (25, 8)
[3, 24, 6, 14]
index: 140 0 counters size: (25, 8)
[8, 9, 22, 19, 15]
index: 141 0 counters size: (26, 8)
[9, 10, 22, 7]
index: 142 0 counters size: (26, 8)
[12, 8, 27, 21, 28]
index: 143 0 counters size: (28, 8)
[21, 2, 18]
index: 144 0 counters size: (30, 8)
[1, 6, 13, 11]
index: 145 0 counters size: (28, 8)
[22, 2, 18]
index: 146 0 counters size: (26, 8)
[16, 27, 7, 14]
index: 147 0 counters size: (28, 8)
[27, 1, 10, 3]
index: 148 0 counters size: (28, 8)
[17, 3]
index: 149 0 counters size: (28, 8)
[22, 16]
index: 150 0 counters size: (26, 8)
[25, 16, 10]
index: 151 0 counters size: (26, 8)
[8, 10, 11]
index: 152 0 counters size: (25, 8)
[20, 9, 14, 5, 27]
index: 153 0 counters size: (27, 8)
[28, 23, 18, 10]
index: 154 0 counters size: (29, 8)
[25, 12]
index: 155 0 counters size: (29, 8)
[6, 23]
index: 156 0 counters size: (27, 8)
[26, 24, 22, 6]
index: 157 0 counters size: (27, 8)
[23, 16, 13]
index: 158 0 counters size: (26, 8)
[16, 5, 4, 6]
index: 159 0 counters size: (26, 8)
[16, 3, 14]
index: 160 0 counters size: (24, 8)
[8, 4]
index: 161 0 counters size: (25, 8)
[21, 13, 12]
index: 162 0 counters size: (25, 8)
[8, 14, 5, 10]
index: 163 0 counters size: (26, 8)
[6, 18, 24, 20, 19]
index: 164 0 counters size: (29, 8)
[26, 22]
index: 165 0 counters size: (28, 8)
[20, 11, 10, 5]
index: 166 0 counters size: (30, 8)

[3]
index: 167 0 counters size: (28, 8)
[15, 12, 4, 8, 7]
index: 168 0 counters size: (31, 8)
[18]
index: 169 0 counters size: (29, 8)
[21, 10, 27]
index: 170 0 counters size: (27, 8)
[5, 1]
index: 171 0 counters size: (24, 8)
[14, 8, 5]
index: 172 0 counters size: (22, 8)
[17, 14, 13, 22]
index: 173 0 counters size: (22, 8)
[1, 11]
index: 174 0 counters size: (22, 8)
[9, 20, 3, 8, 7]
index: 175 0 counters size: (26, 8)
[24, 6, 3, 10, 8, 14]
index: 176 order of [13, 19, 20, 38, 39, 44]: [24, 6, 3, 10, 8, 14] , [Max, Min]: [24 , 3 , 10.833333333333334]
ordered: [ 3  6  8 10 14 24] count :6 counters size: (30, 8)
[21, 15, 19, 24, 23]
index: 177 0 counters size: (30, 8)
[8]
index: 178 0 counters size: (27, 8)
[7, 14, 11, 4]
index: 179 0 counters size: (28, 8)
[23, 4, 30]
index: 180 0 counters size: (30, 8)
[22, 25, 20]
index: 181 0 counters size: (28, 8)
[11]
index: 182 0 counters size: (28, 8)
[21, 18, 7, 29]
index: 183 0 counters size: (29, 8)
[15, 14]
index: 184 0 counters size: (29, 8)
[27, 8, 14, 1]
index: 185 0 counters size: (30, 8)
[8, 14, 13]
index: 186 0 counters size: (29, 8)
[20, 14, 13]
index: 187 0 counters size: (28, 8)
[10, 14]
index: 188 0 counters size: (26, 8)
[21, 9, 15]
index: 189 0 counters size: (25, 8)
[1, 7, 11]
index: 190 0 counters size: (25, 8)
[25, 3, 21]
index: 191 0 counters size: (26, 8)
[8, 25, 3, 4, 16]
index: 192 0 counters size: (27, 8)
[1, 14, 12]
index: 193 0 counters size: (27, 8)
[3, 19, 16]
index: 194 0 counters size: (27, 8)
[17, 20, 28, 27, 8]
index: 195 0 counters size: (29, 8)
[26, 23]
index: 196 0 counters size: (29, 8)
[24, 5, 1]
index: 197 0 counters size: (27, 8)
[21, 4, 14]
index: 198 0 counters size: (27, 8)

In [ ]:
#COUNTERS_DF
t = COUNTERS_DF 
##t.asign+ position pd.Series(np.array(range(1,49,1)), index=COUNTERS_DF.index)
t['position'] = pd.Series(np.array(range(1,COUNTERS_DF.index.size+1,1)), index=COUNTERS_DF.index)
#t.assign('postion' = pd.Series(np.array(range(1,COUNTERS_DF.index.size+1,1)), index=COUNTERS_DF.index))
print(COUNTERS_DF.index.size)
k=[1,25,41,40,37,49,5,6,42,48,13,17,18,29,38,39,3,8,43,36,45,46,47,44,32,35,33,9,30,2,7,24,22,20,19,16,14,10,28]
np.sort(k)

In [ ]:
COUNTERS_DF.shape

display(dt.iloc[1:58,0:7].style)

In [ ]:
print("c20:" + str(20*19*18*17*16*15 /(6*5*4*3*2*1)))
print("c18:" + str(18*17*16*15*14*13 /(6*5*4*3*2*1)))
print("c15:" + str(15*14*13*12*11*10 /(6*5*4*3*2*1)))

<a id='s10'></a>

<a href='#the_destination'>Link to the destination'</a>

In [ ]:
a=[31,3,5,9,34,48,47,44,43,42,37,1,33,2,25,19,17,12,11,49]
np.sort(a)

In [ ]:
dt.iloc[0:3,0:7].style

In [ ]:
dt.iloc[0:3,:].style

In [ ]:
#kt = dt.iloc[0:200,:]
kt=dt
kt['even'] = pd.Series(np.zeros((kt.index.size,), dtype=int), index=kt.index)
kt['odd']  = pd.Series(np.zeros((kt.index.size,), dtype=int), index=kt.index)
kt['high'] = pd.Series(np.zeros((kt.index.size,), dtype=int), index=kt.index)
kt['low']  = pd.Series(np.zeros((kt.index.size,), dtype=int), index=kt.index)

#kt

In [ ]:
low_number_till=30
for index, row in kt.iterrows() :
    #for i in row
    #print(str(index) + str(row))
    even = [i for i in row[1:7] if i%2==0]
    odd  = [i for i in row[1:7] if i%2!=0]
    high = [i for i in row[1:7] if i>low_number_till]
    low  = [i for i in row[1:7] if i<low_number_till]
    print(row[1:7])
    print(high)
    print(len(high))
    #print(low)
    #display(row)
    kt.at[index,'even'] = np.count_nonzero(even)
    kt.at[index,'odd']  = np.count_nonzero(odd)
    kt.at[index,'high'] = len(high)
    kt.at[index,'low']  = len(low)
    #print(even)
#kt
    #print(len(even))

In [ ]:
#np.zeros((kt.index.size,), dtype=int)

In [ ]:
#pd.Series(np.zeros((kt.index.size,), dtype=int), index=kt.index)

In [ ]:
#range(1,kt.index.size+1,1)

In [ ]:
kt.index.size

In [ ]:
#print(kt.to_string())
kt